name: Build and Publish Docker image (unit + integration + push)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  GOFLAGS: -mod=mod

jobs:
  test:
    name: Run tests (unit + integration)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Set OWNER_LC env (lowercase repo owner)
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/.modcache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download

      - name: Run unit tests (exclude integration)
        run: |
          set -euxo pipefail
          PKGS="$(go list ./... | grep -v -E '(^|/)(tests/integration|tests/e2e)$')"
          echo "Testing packages:"
          echo "$PKGS"
          go test $PKGS -v

      - name: Install envtest binaries (kube-apiserver, etcd, kubectl)
        run: |
          set -euxo pipefail
          mkdir -p ./testbin
          # download envtest binaries into ./testbin and print path
          go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use --bin-dir ./testbin --force

      - name: list envtest binaries
        run: |
          echo "KUBEBUILDER_ASSETS=${{ github.workspace }}/testbin"
          ls -la ./testbin || true

      - name: Run integration tests (envtest)
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/testbin
        run: |
          go test ./tests/integration -v -count=1

  build-and-push:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure OWNER_LC env available (job step)
        # if OWNER_LC was set in test job it will be in that job's env only; we set it again here
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/secrets-manager-api:latest
            ghcr.io/${{ env.OWNER_LC }}/secrets-manager-api:${{ github.sha }}
