name: Build and Publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Workflow-level permissions (minimum)
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    # Job-level permissions — explicit so org / repo overrides are less surprising
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # If you have a CR_PAT secret (Personal Access Token), use it.
      # This step runs only when the CR_PAT secret exists and is non-empty.
      - name: Login to GitHub Container Registry (using CR_PAT)
        if: ${{ secrets.CR_PAT }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Otherwise fall back to the built-in GITHUB_TOKEN.
      - name: Login to GitHub Container Registry (using GITHUB_TOKEN)
        if: ${{ !secrets.CR_PAT }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show which token we used (diagnostic)
        run: |
          if [ -n "${{ secrets.CR_PAT }}" ]; then
            echo "Using CR_PAT (personal access token) for GHCR login"
          else
            echo "Using GITHUB_TOKEN for GHCR login"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ toLower(github.repository_owner) }}/secrets-manager-api:latest
            ghcr.io/${{ toLower(github.repository_owner) }}/secrets-manager-api:${{ github.sha }}
